[[section-solution-strategy]]
== Solution Strategy

==== Technology Decisions

For developing Viade we will be following the next strategy (the necessary reasoning of our decisions is explained in section 9):

* **React**. To achieve a responsiveness interface, adaptable to all kind of devices, this framework will be used.
* **Solid libraries**. These libraries will allow the application to communicate in a simpler way.
** Solid File Client.
** Solid Auth Client.
* **Jest and Enzyme**. This library is used to get a tested environment. Each functionality should be tested in order to asure its proper execution.
* **Leaflet**. Library used to display the maps in the application. It's an open source software, and allows to create several types of maps, with functions like geosearching and more.
* **JawgMaps**. This library is used for a more specific functionality, i.e. the elevation for each of the trackpoints of a route.


==== Organizational Decisions

To achieve the best, possible result, there are several decisions:

* Agile development: the use of Scrum, with its guidelines like following a kanban, creating issues to enhance communication in the team, and giving specific feedback in results of functionalities.

* Testing: this decision, although it will be a disadvantage in the short run, will also be a good advantage in the long run in order to achieve a better result for each functionality.