[[section-concepts]]
== Cross-cutting Concepts

.Routes

The basic type of information stored, and showed in our application will be about routes. A route represents a trajectory formed by different points on a the real world. 

They will be able to be stored into the Pod of each user, decoupled from the rest of the application. Routes will be shown to the user employing a graphical interface, preferably a full-fledged map.

.Modules and libraries
We used several modules/libraries that made several of the funcionalities possible and without them it would have been impossible for us to develop them, some of the libraries/modules are listed and explained next.

* solid-auth-client : use the login system most of the time
* solid-file-client : get and upload files from/to the pods
* react-router-dom : use a lot of things as redirects and assigning components to a url from react
* react-toastify : implement notifications
* google-maps-react : show the routes in the map
* @solid/react : use ldflex to get user info
* jest-cucumber : for testing
* jest-puppeteer : for testing